### ISSUE TITLE
META_SITE_PROTOCOL is not set

### ISSUE THREAD

**Issue by taharushain** [nephila/django-meta#104]
I tried implementing the package through a model approach as well as view but in both cases I get this error when I visit the page. According to the documentation, this property is loaded from setting but I have set

`SITE_PROTOCOL='https'`

I also tried overriding the function in view but that didnt work as well. Any idea how to resolve this?

```
def get_protocol(self):
        if not settings.SITE_PROTOCOL:
            return 'https'
        else:
            return 'https'
            # raise ImproperlyConfigured('META_SITE_PROTOCOL is not set')
        return settings.SITE_PROTOCOL
````

**Comment by yakky** [comment]
@taharushain the setting is called `META_SITE_PROTOCOL`, so in your `settings.py` you should have `SITE_PROTOCOL='https'`

**Comment by yakky** [comment]
:+1:
