### ISSUE TITLE
meta tags not showing in head section 

### ISSUE THREAD

**Issue by gibmax** [nephila/django-meta#105]
Hello, I have installed django-meta 1.6.1 in my project using Django 3.0.5 on localhost (Ubuntu 18.04). I added the following as per the docs:

1. 'meta' in ``settings.py``
2.  ``_base.html``
```html
{% load sekizai_tags meta %}
<html {% render_block 'html_extra' %}>
<head {% meta_namespaces %}>
  {{ meta.og_description }}
  {% include "meta/meta.html" %}
  {% block css %}
   ....
   ....
```
3. Apps View:
```python
from meta.views import Meta
def HomeView(request):
    meta = Meta(
        title="Sam's awesome ponies",
        description='Awesome page about ponies',
        keywords=['pony', 'ponies', 'awesome'],
        extra_props = {
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    .....
    .....
```
The meta tags are not showing up in head section. Not able to get this working. 
Please let me know if there is anything I am missing. Thanks!

**Comment by yakky** [comment]
@gibmax if you use function based vieews, you must explicitly pass `meta` to the view context when rendering. From you code snippet (I reformatted in for clarity) it's not clear if you that's the case in your code

**Comment by gibmax** [comment]
@yakky I wasn't passing the meta to the view context. I have added it now and the meta tags are displaying for the function based views. thank you!

**Comment by yakky** [comment]
@gibmax thanks for the update. I amended the documentation to clarify the usage in function based views, feel free to check and suggest improvements
