### ISSUE TITLE
Only displayed og:image:secure_url

### ISSUE THREAD

**Issue by IRIDON** [nephila/django-meta#107]
Hi, after adding secure_url I had a problem. In the specification it is written that from secure_url it is necessary to add also og: image https://ogp.me/. FB debuger say - "The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags."

```
<meta property="og:image" content="http://example.com/ogp.jpg" />
<meta property="og:image:secure_url" content="https://secure.example.com/ogp.jpg" />
```

**Comment by yakky** [comment]
@IRIDON thanks for reporting. Linked PR should solve the issue
