### ISSUE TITLE
get_meta_image not working?

### ISSUE THREAD

**Issue by klimanek** [nephila/django-meta#11]
Hi, all methods like get_meta_description/title/keywords etc. work but `get_meta_image` does absolutely nothing. Image path is stored in db as a string, and calling self.object.img_url works, too (tested in get_meta_description where `self.object.description + self.object.img_url` is returned).  Any ideas? (Django 1.7, django_meta-0.3.1)

Edit: Just adding some info. I am trying to use og meta tags. `<meta property="og:title" ...` and `<meta property="og:description..."` do get displayed in HTML source, `og:image` does not.

**Comment by yakky** [comment]
Could you provide more context / code snippet to understand the issue? What's ``self.object`` in this context? How is the Meta object instantiated?

**Comment by klimanek** [comment]
Yup, here we go. (I had to translate it a bit.)

```
# models.py
class Article(models.Model):
	title = models.CharField(max_length=160, unique=True)
	perex = models.TextField()
	image_url = models.CharField(max_length=200, null=True, blank=True)
	keywords = models.CharField(max_length=160, null=True, blank=True)
	# ...


# views.py
class ArticleDetail(MetadataMixin, DetailView):
    model = Article
    template_name = 'posts/post_detail.html'
    context_object_name = 'article'
    name='articles'
    
    def get_meta_keywords(self, context):
        return self.object.keywords.split(',')

    def get_meta_title(self, context):
        return self.object.title

    def get_meta_description(self, context):
        return self.object.perex # means: Lead paragraph

	def get_meta_image(self, context):
		path_ = self.object.image_url
		return cesta_

# setting.py
META_SITE_PROTOCOL = 'http'
META_SITE_DOMAIN = 'example.com'
META_USE_OG_PROPERTIES = True
# META_IMAGE_URL = 'static'
```

**Comment by yakky** [comment]
@klimanek thanks for the details, I'll have a look at it shortly

**Comment by yakky** [comment]
@klimanek look at linked commit on 1.0b1: this maps exactly to your use case and tests passes. Could you test django-meta 1.0b1?

**Comment by klimanek** [comment]
Still not working for me. No `<meta property="og:image" ...>` in the HTML source codes. However, for now I resolved it by this piece of code that I wrote in `extra_tags.py` under `templatetags` folder. Maybe it will help someone else.

```
@register.simple_tag
def og_image(request):
	path = request.get_full_path()
	domain = request.META['HTTP_HOST']
	default = 'absolute-path-to-your-image'

	img_url = default

	if '/posts/' in path:
		post_slug = path.replace('/posts/', '')

		if len(post_slug) > 0:
			post_slug = post_slug.replace('/', '')

			try:
				post = Post.objects.get(slug=post_slug)
			
				if post.img_url:
					img_url = domain + img_url

			except:
				pass

	return u'<meta property="og:image" content="%s" />' % img_url

```

Then in `base.html` (`<head>...`): `{% og_image request %}`.
