### ISSUE TITLE
Add og:image:alt meta property to views and models

### ISSUE THREAD

**Issue by gibmax** [nephila/django-meta#113]
Hello, I need help adding og:image:alt, og:image:width, og:image:height properties to views and models. I tried adding "og:image:alt" to _metadata for the model and it is not working. Thanks!

**Comment by yakky** [comment]
@gibmax thanks for your input

Managed support for all the image properties will be added via #114 

In the meantime, you can add support for extra image attributes via custom tags support https://django-meta.readthedocs.io/en/latest/extra_tags.html

**Comment by protoroto** [comment]
@yakky @gibmax I'll close this as support for these features was added
