### ISSUE TITLE
Support schema-less urls for images

### ISSUE THREAD

**Issue by therefromhere** [nephila/django-meta#13]
I hit an issue with django-meta where I was using a schema-less URL for my MEDIA_URL (eg //mycdn/ ).

Django-meta doesn't handle this case correctly (Meta.get_full_url() sees the leading / and treats it as a relative URL, so you end up with http://example.com//mycdn/myimage.jpg instead of http://mycdn/myimage.jpg ).

I think the fix is simple (check for // before / and just add self.get_protocol protocol if // is found), I'll add a pull request to cover this.

**Comment by yakky** [comment]
@therefromhere thanks for the report. I'll very much welcome your fix.
