### ISSUE TITLE
Adding meta tags to Flatpages

### ISSUE THREAD

**Issue by philgyford** [nephila/django-meta#142]
I'm using the [Flatpages app](https://docs.djangoproject.com/en/4.1/ref/contrib/flatpages/) and would like to use django-meta's meta tags when rendering a custom template for a Flatpage. But I can't work out if there's a way to hook them together. Some options I've considered:

* I thought about making a proxy model for `FlatPage` and adding a `_metadata` attribute, but I can't see how Flatpages would use that model instead of the original `FlatPage` when rendering a template.
* Or, in order to add a `"meta"` property to the view context, I'd have to entirely replace the two [Flatpages view functions](https://github.com/django/django/blob/main/django/contrib/flatpages/views.py).
* I wondered about adding something in a custom context processor, but that would happen on all pages, and I've already got others working fine in views using `MetadataMixin`.

So I wonder if I'm either missing some sensible way of doing this, or if it's not possible.

(Hope this is an acceptable use of an Issue; please do close it if not, sorry.)

**Comment by yakky** [comment]
@philgyford You can create a templatetag that gets the flat page is input and store the meta objects in the context (eg: `{% flatpage_meta flatpage as meta %}`) which internally instantiates `Meta` and returns the instance
