### ISSUE TITLE
Meta tags escaped in Django 1.9

### ISSUE THREAD

**Issue by tarlabs** [nephila/django-meta#15]
I am using this package with DJango 1.9 and it seems the meta tags are escaped. Making the below changed in meta.py makes it work fine

```
@register.simple_tag
def custom_meta(key, name, value):
    return mark_safe('<meta %s="%s" content="%s">' % (escape(key), escape(name), escape(value)))
```

Can you please check and update ?

**Comment by yakky** [comment]
@tarlabs sure, thanks for reporting this

**Comment by tarlabs** [comment]
@yakky , Found a better solution. You can include the whole meta.html code inside `{% autoescape off %}` and `{% endautoescape %}` tags. So no code change in that case
