### ISSUE TITLE
Upgrading django-meta via PIP forces Django upgrade (1.8 -> 1.9) 

### ISSUE THREAD

**Issue by klimanek** [nephila/django-meta#19]
Trying to upgrade django-meta using PIP. But  it always forces the PIP to download the latest version of Django. This is unwanted behaviour. I wanna keep my 1.8.x installation.

**Comment by yakky** [comment]
@klimanek this is going to be fixed in 1.0 by removing the versioned dependency on django from setup.py.
django-meta 1.0b1 is already available for you to test it

**Comment by klimanek** [comment]
@yakky Thanks for the info. BTW, any progress with the last bug I reported? https://github.com/nephila/django-meta/issues/11

**Comment by yakky** [comment]
Fixed in 1.0.b1
