### ISSUE TITLE
We should complete translations

### ISSUE THREAD

**Issue by thesayfulla** [nephila/django-meta#198]
Translations for this project are still pending. You can find all available translations [here](https://github.com/nephila/django-meta/tree/develop/meta/locale). It would be valuable if you could contribute to the translation of [es](https://github.com/nephila/django-meta/blob/develop/meta/locale/es/LC_MESSAGES/django.po), [nl](https://github.com/nephila/django-meta/blob/develop/meta/locale/nl/LC_MESSAGES/django.po), [pt_BR](https://github.com/nephila/django-meta/blob/develop/meta/locale/pt_BR/LC_MESSAGES/django.po), and [tr](https://github.com/nephila/django-meta/blob/develop/meta/locale/tr/LC_MESSAGES/django.po).

**Comment by thesayfulla** [comment]
> @thesayfulla Hi! I'd love to contribute to those translations, but I really don't know any of those languages. Translations are handled by transifex (see "contributing" section of documentation), so if anyone would like to contribute, let me know and I'll add them to the transifex team.

Hello, how are you? Also I don't know this languages :)
What do you think about google translate?

**Comment by protoroto** [comment]
I'm not a big fan of translating things with Google Translate, as without knowing the language, we could lose a lot of context and provide a wrong translation (that in my opinion is worse than leaving the language in english)

**Comment by thesayfulla** [comment]
Yes. You are right. We could lose context or provide a wrong translation.

**Comment by thesayfulla** [comment]
@protoroto can you add me transifex team? I want to translate uzbek language.

**Comment by protoroto** [comment]
@thesayfulla Sorry, I lost previous message: I've just invited you to transifex, thanks a lot!

**Comment by protoroto** [comment]
@thesayfulla I also added Uzbek language, so you should be set to add translations

**Comment by thesayfulla** [comment]
> @thesayfulla Sorry, I lost previous message: I've just invited you to transifex, thanks a lot!

don't worry please, thank you too!

**Comment by thesayfulla** [comment]
I have completed translation.
![image](https://github.com/nephila/django-meta/assets/61648680/12a9de62-3d15-401c-a80a-7c950ae33b8a)

**Comment by protoroto** [comment]
@thesayfulla Great! I'll try to release a new version next week with your updated translations! Thanks again!

**Comment by protoroto** [comment]
@thesayfulla We've just released 2.4.2 version with your translations! Thanks again!
