### ISSUE TITLE
'sekizai_tags' is not a valid tag library

### ISSUE THREAD

**Issue by tezro** [nephila/django-meta#24]
Hi there. On a clean install in `virtualenv` this error is thrown in templates. This is my part of `reqs.txt`. Python 2.7, MacOS X El Capitan.
```
...
django==1.8.11
django-meta==1.0
...
```

**Comment by yakky** [comment]
Doc is wrong: you must add "sekizai" to ``INSTALLED_APPS``

**Comment by m-vdb** [comment]
idem, pretty annoyed by that...

**Comment by yakky** [comment]
@m-vdb could you check if updated instructions https://github.com/nephila/django-meta/pull/25/files#diff-548eb9ce4cac8e13a1238ad703272931R8 make it clearer?

**Comment by m-vdb** [comment]
makes it clearer but it's a pity that users of this plugin need to do that themselves. I think it should be added to the template tags built-ins in some way, or maybe django-meta's templatetags library should autodiscover those tags.

**Comment by yakky** [comment]
@m-vdb sekizai still require a bit of setup (for contenxt processors). One can remove the sekizai dependency entirely if not using g+ integration or if the required g+ attributes are added manually

**Comment by m-vdb** [comment]
yes I think I'm gonna do that :). I understand

**Comment by yakky** [comment]
@m-vdb alternative approach in #27
