### ISSUE TITLE
Is META_DEFAULT_IMAGE ignored?

### ISSUE THREAD

**Issue by andreyshipilov** [nephila/django-meta#30]
I tried setting `META_DEFAULT_IMAGE` to something like `img/og-image.png` which I tested and it's available by `/static/img/og-image.png`. I also tried setting it to some online available image like `http://example.com/image.png` — still no luck.

Although, when set the context for meta object like `image='img/og-image.png'` — it works as expected.

**Comment by yakky** [comment]
Confirmed. It got lost somewhere.

**Comment by yakky** [comment]
@tezro check linked PR which use META_DEFAULT_IMAGE for view based mixins

**Comment by yakky** [comment]
@andreyshipilov I merged the above PR that will released in version 1.3.  You can verify if current develop fixes your issue
