### ISSUE TITLE
Facebook app_id meta formatting

### ISSUE THREAD

**Issue by chrisforrette** [nephila/django-meta#35]
Hello!

I'd like to first say that I've used `django-meta` on a couple projects now and it's been pretty handy, so thank you for building and sharing it!

Now for the fun stuff—I implemented `django-meta` on a recent project and I noticed several times that, when plugging pages into the Facebook debug tool:

https://developers.facebook.com/tools/debug/

...it would yell at me about a missing `fb:app_id`, which I dismissed because I knew it was in there and everything generally looked fine. But yesterday I implemented the Facebook comments plugin:

https://developers.facebook.com/docs/plugins/comments/

...and set up admin/moderators in the Facebook app and it wasn't working—we couldn't moderate any comments. It took me some time, but I noticed a very subtle difference in how `django-meta` was spitting it out versus how Facebook's documentation was showing it, which was `<meta name="fb:app_id" ...>` and `<meta property="fb:app_id" ...>`, respectively. I worked around it by copying `meta.html` from the source and swapping out the `facebook_prop` template tag for `generic_prop` for the app id, but this seems like something that should go in the source.

I believe the proper fix should be to change the `facebook_prop` template tag to use `property` instead of `name` (`property` seems to be used for all `og:` tags, not just `app_id`, which you can see under "Markup Example" here: https://developers.facebook.com/docs/sharing/webmasters ). I'm happy to put up a pull request for this, just say the word.

Thanks!

**Comment by yakky** [comment]
@chrisforrette thanks for reporting and thorough analysis.
A Pr is ready that should fix the issue. 1.3 is coming soon with this fix
