### ISSUE TITLE
meta.use_facebook AttributeError

### ISSUE THREAD

**Issue by dominicwhite** [nephila/django-meta#37]
I've been trying to incorporate django-meta into a project. However, I running into an issue when putting namespaces into the head tag. Django 1.9 is raising an AttributeError `'dict' object has no attribute 'use_facebook'` at line 197 of `meta/templatetags/meta.py`.

I am having this problem in django-meta 1.2 and 1.3b3. Am I missing something important, or is django-meta failing to set the use_facebook attribute for the Meta class?

The top of my template looks like:
`<!DOCTYPE html>`
`<html>{% load staticfiles %}{% load meta %}`
`<head lang="en" {% meta_namespaces %}>`

In my settings I have:
`META_SITE_PROTOCOL = 'http'`
`META_USE_TITLE_TAG=True`
`META_SITE_NAME = "Site name"`
`META_SITE_DOMAIN = 'Site domain'`
`META_USE_OG_PROPERTIES = True`
`META_USE_FACEBOOK_PROPERTIES = True`

In my view, the context dictionary is:
`    context_dict['meta'] = {`
`        'use_title_tag':True,`
`        'use_facebook':True,`
`        'title':...`
`    }`

**Comment by yakky** [comment]
@dominicwhite are you using the  view-method or model-method to implement the django-meta interface? Could you share a bit of the code you are using?

**Comment by dominicwhite** [comment]
The views-method. The relevant part of the view is:

`def homepage(request):`
`    context_dict = {}`
`    context_dict['meta'] = {`
`        'use_title_tag':True,`
`        'use_facebook':True,`
`        'title':"Sitename",`
`        'description':'Blah',`
`        'keywords':['keyword1']`
`    }`
`    return render(request, 'home/homepage.html', context_dict)`

And the start of the template is:
`<!DOCTYPE html>`
`<html>{% load staticfiles %}{% load meta %}`
`<head lang="en" >`
`    <meta charset="utf-8">`
`    <meta http-equiv="X-UA-Compatible" content="IE=edge" />`
`    <meta name="viewport" content="width=device-width, initial-scale=1">`
`    {% include 'meta/meta.html' %}`

Incidentally, the twitter:domain tag renders with no value if I activate twitter cards (despite specifying my domain name in settings.py).

**Comment by yakky** [comment]
Documentation is actually misleading. You must instantiate a ``Meta`` object and pass it as the ``meta`` context variable:

    meta = Meta(
        title="Sam's awesome ponies",
        description='Awesome page about ponies',
        keywords=['pony', 'ponies', 'awesome'],
        extra_props = {
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        }
        'extra_custom_props': [
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context['meta'] = meta

See http://django-meta.readthedocs.io/en/latest/views.html#meta-objects
I opened a PR to try to clarify this in the docs

**Comment by dominicwhite** [comment]
Thanks, works like a charm
