### ISSUE TITLE
Does it support Django 1.10

### ISSUE THREAD

**Issue by kimond** [nephila/django-meta#41]
In the README it is not explicitly mentioned if `django-meta` is supporting Django 1.10

**Comment by yakky** [comment]
I've not tested it on Django 1.10, but I expect it to work.
I should be able to confirm official support  over the next few days

**Comment by kimond** [comment]
Should you write Django 1.6 and greater instead of all versions explicitly? Like this, we could avoid thinking that the support of Django ends with 1.9.

**Comment by yakky** [comment]
I usually prefer on the safe side and not announce support that's not already tested.
How about something like ``Django: 1.6 to 1.9 (newer versions might work but are not tested yet)``?

**Comment by kimond** [comment]
Seems great. Now, I know it could work with 1.10 but not tested at first sight.

**Comment by yakky** [comment]
@kimond thanks. phrasing updated
