### ISSUE TITLE
MetadataMixin, programmtically generating meta object

### ISSUE THREAD

**Issue by daedelus-j** [nephila/django-meta#43]
Sorry new to django and python, so it's harder for me to debug this.  

os: mac osx 10.11.5
django: 1.9
python: 3.4.3

Since your docs say the `meta/meta.html` partial expects a `meta` context dict, I'm just trying to programmatically pass that dict into context (preferably without touching each view). I poked through the source and decided to try:

Access `get_context_data()`
```
from django.shortcuts import render
from django.views.generic import View
from meta.views import Meta, MetadataMixin

class HomeView(MetadataMixin,View):
    main_template = 'home/main.html'

    def get(self, request):      
        return render(request, self.main_template, context={
            'meta': self.get_context_data(),
        })
```
error:
```
'super' object has no attribute 'get_context_data'

context = super(MetadataMixin, self).get_context_data(**kwargs) # this line
```

Trying to access `get_meta()`:
```
from django.shortcuts import render
from django.views.generic import View
from meta.views import Meta, MetadataMixin

class HomeView(MetadataMixin,View):
    main_template = 'home/main.html'

    def get(self, request):      
        return render(request, self.main_template, context={
            'meta': self.get_meta(),
        })
```
error:
```
Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

Perhaps I missed something in the docs, or perhaps I can help improve the docs. Lemme know if you're missing anything!

**Comment by yakky** [comment]
When using ``MetadataMixin`` just add the properties you need as attributes to the class definition (see https://django-meta.readthedocs.io/en/latest/views.html#view-mixin) and the mixin will automatically populate the context with the right data

**Comment by daedelus-j** [comment]
@yakky Ya i saw that. I guess my question is how to generate all the metadata programmatically from the `setting.py` config?
