### ISSUE TITLE
`META_DEFAULT_IMAGE`, when specified, ignores `META_IMAGE_URL` when it's empty.

### ISSUE THREAD

**Issue by andreyshipilov** [nephila/django-meta#44]
Presumably it should prepend `STATIC_URL`, but looks like it doesn't. Temporary fix is:
```
META_DEFAULT_IMAGE = STATIC_URL + 'img/og-image.png'
```
I see it should be working from code, but:
```
META_DEFAULT_IMAGE = 'img/og-image.png'
```
Results win an `og:image` in meta tags with the URL `'img/og-image.png'`, for some reason.

Thanks ahead

**Comment by yakky** [comment]
@andreyshipilov thanks for reporting this 1.3.2 will fix it
