### ISSUE TITLE
how to set use_ variables at model mixin

### ISSUE THREAD

**Issue by jlariza** [nephila/django-meta#48]
Hello!

I am using the library to display the meta from a model. The problem is that I do not know how to set the following variables for that case:
use_og
use_twitter
use_facebook
use_googleplus
use_title_tag

I checked the html code and it checks this variables to render the related information; but I can not put them as True from the model.

Thank you!

**Comment by yakky** [comment]
They are global settings https://django-meta.readthedocs.io/en/latest/settings.html#meta-use-og-properties
