### ISSUE TITLE
Defferent keyword for different post

### ISSUE THREAD

**Issue by nikolas310** [nephila/django-meta#59]
This plugin works great with django 1.11. But adding individual keywords though blog it separates word as character. Here is my models.py

```
class BlogModel(ModelMeta, models.Model):
    user = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    content = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    keywords = models.CharField(max_length=200, blank=True, null=True)
    

    class Meta:
        verbose_name = 'Blog'

    _metadata = {
        'title': 'title',
        'description': 'content',
        'keywords': 'keywords'
    }
```
I can not understand how can I update keywords as post specific thought plugin itself.

**Immediately what I have done for this:**
in the plugins _view.py_ line no 91
`kws = [k for k in keywords] `changed to `kws = [keywords]`

is there any other solution without modifying the plugin?

**Comment by yakky** [comment]
@nikolas310 values of ``_metadata`` dictionary can be also a callable (or a property) which allows to modify the field value before returning and adding to the ``meta`` object. See https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L197 https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L303 as a reference

**Comment by nikolas310** [comment]
I'm not using djangocms blog. Just using django meta for seo only in my app.

**Comment by yakky** [comment]
Sure: I linked djangocms-blog just an example of implementation on how to handle keywords and splitting keywords using commas

**Comment by nikolas310** [comment]
Thanks @yakky solved the problem by below

`class BlogModel(ModelMeta, models.Model):
    user = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    content = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    keywords = models.CharField(max_length=200, blank=True, null=True)
    

    class Meta:
        verbose_name = 'Blog'

    _metadata = {
        'title': 'title',
        'description': 'content',
        'keywords': 'get_keywords'
    }

    def get_keywords(self):
        return self.keywords.strip().split(',')`

**Comment by yakky** [comment]
@nikolas310 great! Happy to help!
