### ISSUE TITLE
Use of __init__ in MetadataMixin?

### ISSUE THREAD

**Issue by tony** [nephila/django-meta#61]
edit: see below, this is fixed in the develop branch, but causes problems in the latest stable release, 1.3.1

Removing the ``__init__`` and moving the three variable declarations to class variables fixes a few tricky MRO issues with the view.

It's tricky to create a demonstration, but if it's just a mixin, it may be best to avoid using the constructor.

And second, I'm not sure if there's any point to keeping it, since there's no specialized assignment currently there, and ``settings`` is lazily loaded and is ok to put in the class scope.

**Comment by tony** [comment]
In 1.3.1, this causes breaks:

https://github.com/nephila/django-meta/blob/1.3.2/meta/views.py#L149

Since it doesn't call super's ``__init__``.

This is fixed in *develop*:

https://github.com/nephila/django-meta/blob/21e740f083ea32b150ad012c3bc7941ed920de20/meta/views.py#L153

It'd be helpful to tag see if this can be backported to a release.

**Comment by tony** [comment]
This was actually hard to monkeypatch/subclass out locally. So it may be good to tag a release sooner rather than later.

**Comment by yakky** [comment]
Hi @tony I'm sorry we still did not find the time to release 1.4 final yet. To speed up the release process, could you test 1.4rc1 which is already available on PyPi and fix the mentioned issue?

**Comment by tony** [comment]
I'm using develop ATM, i'll switch it to 1.4rc1 tomorrow and start using it.

**Comment by tony** [comment]
And I'll report back if it works stable

**Comment by yakky** [comment]
@tony thanks! (develop and 1.4rc1 are the same, actually. 1.4rc1 it's just the packaged version)

**Comment by tony** [comment]
Good to know!

thank you. I will come back with info tomorrow. Just FYI I used *develop* all day today and so far all is fine. 👍

**Comment by tony** [comment]
@yakky I'm using this a live website. While I haven't tested every last thing. I have basic meta tags, OG, and twitter cards working:

https://twitter.com/develdottech/status/894341705335541763

**Comment by yakky** [comment]
@tony thanks for sharing! I should be able to release 1.4 today

**Comment by yakky** [comment]
Sorry I haven't updated this after release :)
1.4 has been released, closing this
