### ISSUE TITLE
og:latitude and og:longitude implementation of meta tags for opengraph needs to be there.

### ISSUE THREAD

**Issue by daxbritto** [nephila/django-meta#63]

**Comment by yakky** [comment]
Nice suggestion. We can add them explicitly, in the meantime you can use `extra_custom_props` to generate them yourself https://django-meta.readthedocs.io/en/latest/views.html#extra-props

**Comment by yakky** [comment]
you may want to check #95 (and https://github.com/nephila/django-meta/pull/95/files#diff-823680934ff274e0f1ecdacdf80a9f61R3 in detail) regarding implementing extra / custom tags properties
