### ISSUE TITLE
Support for current domain (from request)

### ISSUE THREAD

**Issue by Paul424** [nephila/django-meta#65]
Currently when configuring to use the sites framework it will raise an exception when SITE_ID is not set.

This caused by Site.objects.get_current not being passed the request which is obviously available in both the views and models...

return Site.objects.get_current().domain

Could an optional request be added to the init and passed along?

**Comment by yakky** [comment]
Yeah, I think it's a pretty sensible thing to do, thanks for the suggestion

**Comment by yakky** [comment]
@Paul424 PR added, if you want to have a look at it
