### ISSUE TITLE
How to use custom function for a meta tag

### ISSUE THREAD

**Issue by Logmytech** [nephila/django-meta#66]
I want to add something to a meta tag or change it in some way.

I currently do
```
_metadata = {
        'title' : 'title'
    }
def get_title_meta(self):
    return self.title+ self.topic.title
```

I'm using `title`, but I want to use `get_title_meta` for the title meta tag.

How do I achieve this?

**Comment by yakky** [comment]
Just put the name of the callable as a value for the dictionary key (`get_title_meta` in your example above) 
See https://django-meta.readthedocs.io/en/latest/models.html#concepts for documentation and here https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L210 for a usage example

**Comment by yakky** [comment]
@Logmytech I'm closing this. Feel free to pop into https://gitter.im/nephila/applications chat if you need more clarifications.
