### ISSUE TITLE
How to use different data for of OpenGraph and normal tags

### ISSUE THREAD

**Issue by Logmytech** [nephila/django-meta#67]
I want to display different metadata for facebook and search engines.

Like reddit does.

For example for normal description tag reddit shows "Reddit! The frontpage of the internet".
For OGP it shows "256 points and 56 comments"

ie OGP and normal metadata

How do I do this?

**Comment by yakky** [comment]
It's perfectly feasible. Each tag can be populated in a completely indipendent way.
Are you using django-meta at view or model level? In the first case you just pass the "right" value to the attribute (https://django-meta.readthedocs.io/en/latest/views.html#meta-objects), in the second, you can customize `_metadata` attribute to pick whatever field / constant you feel like https://django-meta.readthedocs.io/en/latest/models.html#usage

**Comment by yakky** [comment]
I'm closing this. Feel free to pop into https://gitter.im/nephila/applications chat if you need more clarifications.
