### ISSUE TITLE
Question: Is there a reason meta title and og:title are the same?

### ISSUE THREAD

**Issue by chrisforrette** [nephila/django-meta#78]
I've been recently implementing `django-meta` into a project and noticed that `<title>` and `<meta property="og:title" />` both use the same exact variable (`title`) as opposed to `description`, which has a specific, optional `og_description`, that falls back to `description`.

I'm wondering if there's intention behind this (maybe I'm unaware of a best practice?) or if a PR to making it more like the `description` property would be welcome?

Thanks!

**Comment by yakky** [comment]
#72 takes care exactly of this issue :smile:

**Comment by yakky** [comment]
Fixed in #72
