### ISSUE TITLE
og:image and og:image:secure_url

### ISSUE THREAD

**Issue by fsbraun** [nephila/django-meta#79]
It seems that Facebook does not pick up meta tags with the property ``og:image`` and an URL that is secure (https). If I understand correctly, instead the property ``og:image:secure_url`` should be used for https. This leads to lost images of any shares of my secure web site on facebook.

Suggestion: Can django-meta check of the URL is secure and add an ``og:image:secure_url`` tag in this case?

Similarly ``og:video`` and ``og:audio`` have secure_url pendants.

Best regards, Fabian

PS: See this [Stackoverflow](https://stackoverflow.com/questions/8855361/fb-opengraph-ogimage-not-pulling-images-possibly-https) article

**Comment by dwjorgeb** [comment]
this is causing a bug with the latest version of FB, which is disregarding the og:image:secure_url tag, it needs to be just og:image

See https://stackoverflow.com/a/56466941/1594402

**Comment by db654** [comment]
> this is causing a bug with the latest version of FB, which is disregarding the og:image:secure_url tag, it needs to be just og:image
> 
> See https://stackoverflow.com/a/56466941/1594402

Seconding this. When only the og:image:secure_url is present, the facebook debugger returns this:
`The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.`

**Comment by yakky** [comment]
@db654 @dwjorgeb thanks for the head's up.
I'm investigating this, in the meantime you can disable the `secure_url` postfix by setting `META_OG_SECURE_URL_ITEMS = []`

**Comment by picturedots** [comment]
@yakky 's tip worked for me.

**Comment by IRIDON** [comment]
Hi, after adding secure_url I had a problem. In the specification it is written that from secure_url it is necessary to add also og: image https://ogp.me/

<meta property="og:image" content="http://example.com/ogp.jpg" />
<meta property="og:image:secure_url" content="https://secure.example.com/ogp.jpg" />
