### ISSUE TITLE
META_TWITTER_TYPE settings not working in MetadataMixin

### ISSUE THREAD

**Issue by arthur-wsw** [nephila/django-meta#80]
I'm using MetadataMixin in my views and was unable to add the twitter:card globally using settings.

In [settings documentation](https://django-meta.readthedocs.io/en/latest/settings.html#other-settings) there is META_TWITTER_TYPE that work great with ModelMeta by adding twitter_type in context.

In MetadataMixin twitter_type is not added in context, instead twitter_card is set. But twitter_card value could only be set in views not in settings.

 Should it be best to: 
1. Add another META_TWITTER_CARD settings and read this as default value in MetadataMixin
2. Normalise the twitter_type and twitter_card in ModelMeta and MetadataMixin to use only one term

I'll make a PR with solution 1. If solution 2 looks better for you, let me know and i'll try to do it.

**Comment by yakky** [comment]
I would prefer the second option as it would fix the root issue

**Comment by yakky** [comment]
Fixed by #111 
Thanks @arthur-wsw for raising this
