### ISSUE TITLE
meta.views.Meta ignores some keys

### ISSUE THREAD

**Issue by madEng84** [nephila/django-meta#82]
Hi guys,
when I pass my seo metadata to `meta.views.Meta.__init__` function, some keys are ignored because the `__init__` function get from `**kwargs` only what it needs.

So if I pass my Meta object to the template, I cannot find these attributes used by the template `meta/meta.html`:

- og_author_url
- og_author
- og_publisher
- og_profile_id
- tag

It seems that the same happens if I use a DjangoModel that inherits from meta.ModelMeta and I pass to the context my DjangoModel().as_meta() object

What am I doing wrong?

p.s.
I'm using `django-meta==1.4.1`

Thanks in advance

**Comment by yakky** [comment]
Hi @madEng84 
with `ModelMeta` you can define the dictionary returned to the context by overriding the `_metadata` attribute. It will explicitly set the attributes on the resulting `Meta` instance, thus any key in `_metadata` will be set in the `Meta` instance

in `Meta` you have `extra_props` / `extra_custom_props` to customize the rendered meta tags (see https://django-meta.readthedocs.io/en/latest/views.html#extra-props)

**Comment by yakky** [comment]
@madEng84 you may want to check #95 (and https://github.com/nephila/django-meta/pull/95/files#diff-823680934ff274e0f1ecdacdf80a9f61R3 in detail) regarding implementing extra / custom tags properties

**Comment by madEng84** [comment]
@yakky great!
Thank you
