### ISSUE TITLE
Add audio and video support

### ISSUE THREAD

**Issue by Myzel394** [nephila/django-meta#92]
Audio and video support would be great. You only need to add it for og and twitter.

**Comment by yakky** [comment]
What do you mean with audio and video support?

**Comment by Myzel394** [comment]
Take a look at this: https://ogp.me/#type_music and this: https://ogp.me/#type_video

**Comment by yakky** [comment]
@Myzel394 thanks for the pointers
I think the best solution would be to make easier to implement extended objects. Both OpenGraph and Schema.org are extremely rich and we can't possibly support all the object types.
But making easy to add support for your own is definitely in scope.
I will think about possible a possible solution for this

**Comment by yakky** [comment]
(you can alredy provide your custom objects via extra_props / custom_props (https://django-meta.readthedocs.io/en/latest/views.html#extra-props) but I agree they might be cumbersome to use if you have a complex object type

**Comment by yakky** [comment]
@Myzel394 you may want to check #95 (and https://github.com/nephila/django-meta/pull/95/files#diff-823680934ff274e0f1ecdacdf80a9f61R3 in detail) regarding implementing extra / custom tags properties
